[project]
name = "dingtalk-http"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.121.1",
    "pycryptodome>=3.23.0",
    "uvicorn[standard]>=0.38.0",
]
